### ISSUE TITLE
Error while running playbook

### ISSUE THREAD

**Issue by pkmishra** [jtyr/ansible-stunnel#2]
Following error is thrown when running playbook
```
FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute u'service'\n\nThe error appears to have been in '/jtyr.stunnel/tasks/main.yaml': line 30, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  with_dict: \"{{ stunnel_service_script }}\"\n- name: Install Stunnel service script\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute u'service'"}
```
Fix is to replace the code with following code
```
- name: Install Stunnel service script
  copy:
    src: "{{ item.value.src}}"
    dest: "{{ item.value.dest}}"
    mode: "{{ item.value.mode | default('0644') }}"
  when: >
    stunnel_service_install
  with_dict: "{{ stunnel_service_script }}"
  tags:
    - stunnel_service
```

**Comment by jtyr** [comment]
Thanks for opening this issue. The core should work as it is. You just needs to gather fats from the from the remote machine in order to have the `ansible_service_mgr` variable available:

```yaml
- name: My play
  hosts: all
  # This should not be necessary as the facts gathering is enabled by default
  gather_facts: yes
  roles:
    - stunnel
```
